services:

    idci_request_theme.event_subscriber.theme:
        class: IDCI\Bundle\RequestThemeBundle\EventSubscriber\ThemeEventSubscriber
        tags:
            - { name: kernel.event_subscriber }

    idci_request_theme.theme_registry:
        class: IDCI\Bundle\RequestThemeBundle\Theme\ThemeRegistry

    idci_request_theme.theme:
        class: IDCI\Bundle\RequestThemeBundle\Theme\Theme
        arguments: [null, null, null]
        abstract: true